//! The kernel set, by name, with each op's layout contract.
//!
//! The CUDA implementation is `cuda/kernels.cu` (embedded as [`crate::FATBIN`]);
//! the CPU implementations, which keep the same arithmetic so a backend
//! difference is a real one, are in [`cpu`]. An engine looks kernels up by name,
//! so
//! this table is the toolkit's public surface: [`NAMES`] is what
//! `Module::func` will successfully resolve, and [`OPS`] carries the one-line
//! contract each op obeys.

pub mod cpu;

/// One kernel: its fatbin name and the layout contract it implements.
///
/// No `PartialEq`: two `fn` pointers are not reliably comparable.
#[derive(Debug, Clone, Copy)]
pub struct Op {
    pub name: &'static str,
    pub doc: &'static str,
}

/// Every kernel the toolkit ships, in the order `cuda/kernels.cu` declares them.
pub const OPS: &[Op] = &[
    Op { name: "lg_noop", doc: "Trivial entry point: loading the module and calling this proves the whole driver path works (`lightgpu`'s `gpuinfo` does exactly that)." },
    Op { name: "lg_rms_norm", doc: "RMSNorm (Qwen2 LM): y = x * rsqrt(mean(x^2) + eps) * w, per-row." },
    Op { name: "lg_layer_norm", doc: "LayerNorm: y = (x - mean) * rsqrt(var + eps) * w + b, per-row." },
    Op { name: "lg_layer_norm_2pass", doc: "LayerNorm, two-pass form (mean, then the variance of (x - mean)). Stabler when the mean is large relative to the spread; see the note above on why it is not the default for the LocateAnything checkpoints." },
    Op { name: "lg_rope_neox", doc: "NEOX (half-split) convention - Qwen2 LM. head_dim must be even. x: [hd, nh, ntok] (hd contiguous), pair i <-> i + hd/2, pos per token." },
    Op { name: "lg_rope_2d", doc: "2-D RoPE (MoonViT): head_dim split into adjacent pairs; cos/sin tables are precomputed host-side (they depend on the token grid) and passed as [n_pairs, ntok]." },
    Op { name: "lg_silu_mul", doc: "y = silu(gate) * up" },
    Op { name: "lg_gelu_tanh", doc: "y = 0.5 x (1 + tanh(sqrt(2/pi) (x + 0.044715 x^3)))" },
    Op { name: "lg_gelu_erf", doc: "GELU, erf form: y = 0.5 x (1 + erf(x / sqrt(2)))" },
    Op { name: "lg_relu", doc: "y = max(x, 0), elementwise over n elements. The plain ReLU, with no slope argument (contrast `lg_lrelu`)." },
    Op { name: "lg_sigmoid", doc: "y = 1 / (1 + exp(-x)), elementwise over n elements. A standalone op rather than something folded into a fused kernel, because three engines need it alone (MAXIM's CALayer, lama's output layer, rmbg's attention). NCHW-agnostic: any length, and `y` may be the same buffer as `x`." },
    Op { name: "lg_add", doc: "y = a + b" },
    Op { name: "lg_mul", doc: "y = a * b, elementwise over n elements, out-of-place. The multiplicative twin of `lg_add`, and the op every GATED architecture needs on its own: NAFNet's SimpleGate multiplies the two halves of a channel split, MAXIM's gMLP multiplies a gate by a value. Promoted from MAXIM's mx_mul under the 'plausibly used by another family' rule in docs/MAINTAINING.md. NOT `lg_silu_mul`, which is a fused in-place gated-MLP step, and NOT a fold of a broadcast multiply, which scales every channel by one shared spatial map and is the scalar `a[0]` at hw == 1." },
    Op { name: "lg_add_inplace", doc: "y += x, in place. The second in-place op in this file, and for the same reason as `lg_silu_mul`: a residual accumulate where an out-of-place form would need one more buffer of the activation size per layer." },
    Op { name: "lg_scale", doc: "y = x * s (scalar)" },
    Op { name: "lg_row_affine", doc: "y[i][j] = x[i][j] * scale[j] (+ shift[j] when non-null). x is [ne0, nrows] with ne0 contiguous, so the per-row vector is indexed by the CONTIGUOUS dimension. MERGE DECISION: this replaces lg_add_bias (scale=1). CORRECTION: it does NOT subsume a per-channel affine over NCHW - that op indexes its vector by CHANNEL, and no choice of ne0/nrows reproduces it because NCHW fixes which dimension is contiguous. Use lg_channel_affine for that." },
    Op { name: "lg_channel_layer_norm", doc: "LayerNorm over the CHANNEL axis of an NCHW tensor: for each of the hw spatial positions, normalize the c values spaced hw apart, with w/b indexed by channel. Distinct from lg_layer_norm, which normalizes the CONTIGUOUS ne0 within each row and therefore reads the wrong axis whenever an NCHW tensor has hw > 1. One thread per spatial position, walking the c values serially with NO shared memory and no block-wide reduction: launch with grid = div_ceil(hw, blockDim) and any blockDim, which need not match the c the reduction runs over (blockDim 256 with c=32 was the old form's worst case). Distinct from lg_channel_mean, which reduces per channel and whose summation order is contractual; here the order is a plain ascending serial sum." },
    Op { name: "lg_channel_affine", doc: "NCHW per-CHANNEL affine: out[c][p] = in[c][p] * scale[c] + shift[c], p over each channel's contiguous hw. The folded-BatchNorm op. Either scale or shift may be null (pure scale / pure bias), and `in` may alias `out`. NOT expressible with lg_row_affine, which indexes the CONTIGUOUS dimension - for NCHW that is the width, not the channel." },
    Op { name: "lg_channel_scale", doc: "out[c][p] = in[c][p] * s[c] - the `shift = null` specialisation of lg_channel_affine, kept as its own entry point because its three-pointer (in, s, out) argument order is what the scale-only callers already build. Use it where `s` is an activation rather than a weight." },
    Op { name: "lg_copy", doc: "y = x, n elements. Kept as a kernel because engines use it to make an explicit device-side copy when they cannot alias the buffer." },
    Op { name: "lg_channel_mean", doc: "Per-channel spatial mean over an NCHW plane: out[c] = mean_p in[c][p], one block per channel, grid = (c, 1, 1). SUMMATION ORDER IS THE CONTRACT: strided per-thread partials (i = t, t + blockDim, ...) followed by a halving tree over the full 1024 scratch slots, so it needs no power-of-two block and has no unpaired-partial case. The CPU twin reproduces that order for the same block size, so a backend difference is a bug and not a reordering. Static shared scratch (1024), so the caller passes NO dynamic shared memory." },
    Op { name: "lg_argmax", doc: "Argmax over the ne0 rows of a [ne0, ncols] buffer, one block per column. Also writes the max value." },
    Op { name: "lg_conv1x1", doc: "out[n][oc][y][x] = bias[oc] + sum_ic w[oc][ic] * in[n][ic][y][x]" },
    Op { name: "lg_conv3x3s1p1", doc: "3x3, stride 1, pad 1. Accumulation order matches the CPU twin: ky, kx, ci." },
    Op { name: "lg_conv3x3_winograd", doc: "3x3, stride 1, pad 1 - the SAME op as lg_conv3x3s1p1, with an F(4x4,3x3) Winograd implementation: 4/9ths the multiplies at the cost of a transform. Same layout and weight order ([c_out][c_in][3][3], ci contiguous). Extra args: c_chunk (input-channel chunk), ocb (output channels per CTA, <= 16), act (0 none, 1 relu, 2 lrelu with slope act_p). grid = (ceil(wd/16), ceil(h/16), ceil(c_out/ocb)), block = (256,1,1), shared = (c_chunk*16 + c_chunk*ocb)*36 floats. Choose by c_in: it LOSES at c_in=3, where the transform is not amortised, and wins from c_in=32 up." },
    Op { name: "lg_conv3x3_tile", doc: "3x3, stride 1, pad 1 - the SAME op as lg_conv3x3s1p1, with the input tile and the weight tile staged in shared memory and eight accumulators per thread instead of one. Same layout and weight order ([c_out][c_in][3][3], ci contiguous). THE ACCUMULATION ORDER IS (ci, ky, kx), NOT lg_conv3x3s1p1's (ky, kx, ci), because the channel tile has to be the outer loop; the halo is zero-filled rather than skipped. So the result is NOT BIT-IDENTICAL to lg_conv3x3s1p1 (measured: worst 2.03e-06 at 0..1 scale on 32->32, half the elements differing in the last bits) - this is a magnitude-bound swap, unlike lg_conv1x1_rb/lg_linear_rb, and a caller that needs bit-exactness keeps the direct kernel. Measured 9.7x-18.3x lg_conv3x3s1p1 across c_in 3 to 128 at 512x512 and 7.2x at 1080p, on ONE geometry. Extra args: act (0 none, 1 relu, 2 lrelu with slope act_p - the lg_conv3x3_winograd convention) and BIAS IS APPLIED AFTER the sum, unlike lg_conv3x3s1p1's bias-first. grid = (ceil(wd/128), ceil(h/8), ceil(c_out/8)), block = (32,8,1), 42752 bytes of STATIC shared memory (no dynamic shared memory, and no cudaFuncSetAttribute call is needed)." },
    Op { name: "lg_conv3x3_q2", doc: "3x3, stride 1, pad 1 - the SAME accumulation as lg_conv3x3_tile, from the PARAMETERISED TILE BODY promoted from hcflow-rs (see the `lg_tile_body` comment in cuda/kernels.cu). THE ACCUMULATION ORDER IS (ci, ky, kx) WITH THE BIAS ADDED AFTER THE SUM, so at the same geometry this is BIT-IDENTICAL to lg_conv3x3_tile and NOT to lg_conv3x3s1p1 - the CPU twin `conv3x3_body` is checked for equality against `conv3x3_tile`, not for a tolerance. `q2` is the tile that won the promoting engine's sweep: 16x8 threads, 4 output columns per thread (64 columns per tile), 8 rows, CIM 2 staged input channels, OC 8, __launch_bounds__(16*8, 8). Extra args: act (0 none, 1 relu, 2 lrelu with slope act_p). grid = (ceil(wd/64), ceil(h/8), ceil(c_out/8)), block = (16,8,1), static shared memory, channels on blockIdx.z." },
    Op { name: "lg_conv3x3_q2ng2", doc: "The SAME OP as lg_conv3x3_q2 with TWO OUTPUT-CHANNEL GROUPS PER BLOCK on threadIdx.z: the block is (16,8,2) and the two groups SHARE one staged input tile, so the staging, its bounds predicates and the input re-read are amortized over twice the arithmetic. It does not hide the staging latency, it amortizes it, and acc[OC][TPX] per thread is unchanged - which is what separates it from raising OC. Measured 1.58x lg_conv3x3_q2 at 128->32 over 512x512 and 1.17-1.21x on the concatenated form, on the promoting engine; it only pays where there are enough blocks to fill the SMs, so use it above ~160 blocks. THE BLOCK SHAPE IS DIFFERENT, WHICH IS WHY IT HAS ITS OWN NAME. The channel group is on blockIdx.x here, not z, so grid = (ceil(ceil(c_out/8)/2), ceil(h/8), ceil(wd/64)), block = (16,8,2), and 2 MUST DIVIDE ceil(c_out/8) or the tail of the last group goes unwritten. Same accumulation order and so bit-identical to lg_conv3x3_q2." },
    Op { name: "lg_conv3x3_catq0", doc: "lg_conv3x3_q2 reading a CONCATENATION OF UP TO SIX PLANES without materialising it. `in` is the first source; i1..i5 are the rest, and g1..g5 are the CHANNEL INDEX AT WHICH EACH BEGINS in the concatenation, so plane N holds channels [gN, g(N+1)). A dense block grows its input by one plane per layer and a copy of the whole activation per layer is what this avoids. `c_in` is the TOTAL concatenated channel count, and the weight layout is unchanged: [c_out][c_in][3][3] ordered by the CONCATENATED index. The starts must be non-decreasing or the kernel's chain of comparisons picks a later plane for an earlier channel; a missing plane repeats the last start, which keeps them non-decreasing. With every gN at 0 this is lg_conv3x3_q2. Extra args: i1..i5, g1..g5, ng (the number of LIVE starts, 1..=6; ng <= 1 means a single plane). grid and block as lg_conv3x3_q2." },
    Op { name: "lg_conv3x3_catq0ng2", doc: "lg_conv3x3_catq0 with NG = 2, the concatenated form of lg_conv3x3_q2ng2. Same accumulation, same plane list, same channel-start contract; the block gains the threadIdx.z axis and the channel group moves from blockIdx.z to blockIdx.x, so grid = (ceil(ceil(c_out/8)/2), ceil(h/8), ceil(wd/64)), block = (16,8,2). 2 must divide ceil(c_out/8). Measured 1.17-1.21x lg_conv3x3_catq0 on the promoting engine's trunk shapes." },
    Op { name: "lg_conv4x4s4", doc: "4x4 patch embed, stride 4, no padding. Order: ci, ky, kx." },
    Op { name: "lg_conv_kxk", doc: "Generic k x k, stride 1, pad k/2. Order: ky, kx, ci." },
    Op { name: "lg_linear_1x1", doc: "1x1 conv with a 1x1 spatial input (the ASPP gap branch): out[oc] = sum_ic w * x" },
    Op { name: "lg_extract_rows", doc: "dst [nrows, ntok] <- src [src_stride, ntok] (first nrows rows). Used to split the ViT qkv buffer (3456 rows) into q/k/v (1152 rows each). One block per TOKEN: consecutive threads then touch consecutive addresses in both source and destination. Iterating rows with grid.x instead would make every thread in a warp touch a different row, i.e. ~13.8 KB apart - fully uncoalesced (measured: ~1 s of the ViT)." },
    Op { name: "lg_merge_2x2", doc: "2x2 patch merge (MoonViT -> connector), matching merge_patches(): out[m*4C + e_idx*C + d] = vf[tok*C + d] e_idx = b*2+e, tok = (2a+b)*gw + (2c+e), m = a*mw + c" },
    Op { name: "lg_get_row_q8_0_aligned", doc: "Decode helper: dequantize ONE row of an aligned 36-byte q8_0 weight table, with the row index passed as a kernel ARGUMENT (no ids upload). grid = (ceil(ne0/256), 1), block = (256,1,1). Writes ne0 f32." },
    Op { name: "lg_copy_row", doc: "Async device-to-device row append for a KV cache. Replaces per-layer synchronous cuMemcpyDtoD calls that flush the pipeline." },
    Op { name: "lg_set_i32", doc: "Write a single i32 from a host value without a pageable H2D copy (used for the decode position scalar)." },
    Op { name: "lg_attn_gqa", doc: "GQA attention, flash-style: one warp per (query token, query head). q: [hd, n_qh, ntq], k/v: [hd, n_kvh, ntk], out: [hd, n_qh, ntq]; lane l holds the d-slice {l, l+32, ...} and the running (max, denom) is kept per lane in the online-softmax form. Mask, when non-null, is [ntq, ntk] additive - use -FLT_MAX/4 rather than -inf so a fully-masked row still produces a finite output. GQA: n_kvh may be less than n_qh, each kv head serving n_qh/n_kvh consecutive query heads. hd is 128 for the LM and 72 for the ViT, with ceil(hd/32) registers per lane and bounds guards on the ragged tail. Kept alongside lg_attn_flash: this one reads K/V from DRAM per query token and is the right choice for SHORT key sequences (decode), where the shared-memory staging of the flash variant costs more than it saves. grid = (ceil(n_qh*ntq/warps), 1, 1), block = (warps*32, 1, 1)." },
    Op { name: "lg_attn_prefill_scores", doc: "Batched-GEMM prefill attention, stage 1 of 3: s[h][i][j] = scale * dot(q_i, k_j) + mask[i][j]. q: [hd, n_qh, ntq], k: [hd, n_kvh, ntk], s: [n_qh, ntq, ntk] with the head SLOWEST so one head's slice is contiguous; mask (may be null) is [ntq, ntk] additive, use -FLT_MAX/4. A block owns a (query tile x key tile) of one head, stages both in shared memory, then each thread multiplies a 4x4 register block (four query rows against four keys), so each staged value feeds 4 dot products - a straight elementwise sweep was CORRECT BUT NO FASTER (73 ms/layer against 14.1), because a k row was re-read once per query row. ALL THREE STAGES REQUIRE hd <= 128 (LA_HD_MAX): the shared tiles are sized by it. GQA as lg_attn_gqa. grid = (ceil(ntk/32), ceil(ntq/32), n_qh), block = (256,1,1), no dynamic shared memory; only the first 64 threads own a register block, the rest stage and return." },
    Op { name: "lg_attn_prefill_softmax", doc: "Batched-GEMM prefill attention, stage 2 of 3: in-place row softmax over the key axis of s[h][i][:], one block per (head, query), so the max-then-sum two-pass is a block-wide reduction over a contiguous row. exp is taken relative to the row max, and an additive -FLT_MAX/4 mask entry subtracts to exp(-FLT_MAX/4 - m) = 0, dropping out of both numerator and denominator with no special case. A fully-masked row would give l == 0; unreachable for a causal mask, but 1/0 would put NaN in the residual, so it yields a zero row instead. 1.2 ms/layer against 73 ms for the scores stage, so it is deliberately left simple. grid = (1, ntq, n_qh), block = (256,1,1)." },
    Op { name: "lg_attn_prefill_out", doc: "Batched-GEMM prefill attention, stage 3 of 3: out[h][i][d] = sum_j p[h][i][j] * v[j][gq][d]. p is the softmaxed score matrix from stage 2 ([n_qh, ntq, ntk], head slowest), v is [hd, n_kvh, ntk], out is [hd, n_qh, ntq]. A block owns a query tile of one head and all of hd, ONE THREAD PER OUTPUT CHANNEL, with V rows staged a tile at a time - which turns the DRAM traffic from (one V row per output element) into (one V row per block). REQUIRES hd <= 128 (LA_HD_MAX): the block is 128 threads, one per channel. GQA as lg_attn_gqa. grid = (1, ceil(ntq/16), n_qh), block = (128,1,1)." },
    Op { name: "lg_attn_flash", doc: "Self-attention with K/V staged in shared memory (ViT and full prefill). Identical arithmetic to lg_attn_gqa, but a block owns (head, W query tokens) and reads each K/V element from DRAM once per block instead of once per query token. For the ViT the naive version is ~9.7 GB of traffic per layer (~39 ms); staging into smem cuts it by ~W." },
    Op { name: "lg_linear", doc: "Linear on the row-major token layout: out[i*C_out + o] = bias[o] + sum_c x[i*C_in + c] * w[o*C_in + c], accumulated in c order. Tiled 16x16 with the shared-memory trick that makes the weight tile readable as ws[tx][k] against xs[ty][k]." },
    Op { name: "lg_f32_gemm", doc: "Naive one-thread-per-output. Correct and layout-obvious; the tiled variant below is what large shapes should call." },
    Op { name: "lg_f32_gemm_tiled", doc: "f32 GEMM, v8-style tiling: 64 rows x 32 columns per 256-thread block (32 row lanes x 8 column slots, 2 rows x 4 columns per thread = 8 accumulators). The 32 columns' current k-step (one float4 each) is staged in shared memory so the activation float4 is loaded once per block-k-step instead of once per row lane. No k-split: the tiles are numerous enough. grid = (ceil(ne1/64), ceil(ncols/32)). Requires ne0 % 4 == 0." },
    Op { name: "lg_quantize_q8_0", doc: "Standalone activation quantizer: x [ne0, ncols] -> int8 qs [ne0, ncols] + per-32-block f32 scales sc [ne0/32, ncols]. One warp per (block, column). Running this once per GEMM removes the per-row-block recomputation that made the fused dp4a kernel slow. NOTE: scales are stored [ncols][nb] (column-major over blocks) so the GEMM can walk a column's scales with stride 1: sc[c * nb + b]." },
    Op { name: "lg_q8_0_gemm_dp4a", doc: "dp4a GEMM over the ALIGNED 36-byte layout: 64 rows x 32 cols per 256-thread block, 32 row lanes x 8 column slots, 2 rows x 4 columns per thread. The k-block's 32 int8 weights and the staged activation are both read as aligned 4-byte ints (8 int loads per block instead of 64 byte ops). grid = (ceil(ne1/64), ceil(ncols/32))." },
    Op { name: "lg_q8_0_gemm_aligned", doc: "Scalar q8_0 GEMM over the ALIGNED 36-byte layout: one thread per output element, used for the single-column lm_head projection. grid = (ceil(ne1/64), ceil(ncols/32)), block = (256,1,1). y[col][row]." },
    Op { name: "lg_q8_0_gemv", doc: "Decode-oriented q8_0 GEMV (few columns): ONE WARP PER OUTPUT ROW, lane l walking the row's k-blocks in strides of 32 blocks, so for a fixed k-block index the 32 lanes read 32 consecutive 36-byte blocks - perfectly coalesced - and the k-blocks are then reduced across the warp with shuffles. The whole activation row is staged in DYNAMIC shared memory (ne0 bytes) at the top, so the caller passes shared = ne0. An optional output bias serves the decode GEMMs with a bias epilogue. ALIGNED 36-byte layout, as lg_q8_0_gemm_dp4a. grid = (ceil(ne1/8), ncols), block = (32*8, 1, 1). y[col][row]." },
    Op { name: "lg_lrelu", doc: "y = x >= 0 ? x : slope * x, whole-plane, slope as an argument. Distinct from lg_relu, whose `int n` token-length signature does not carry a float operand." },
    Op { name: "lg_add_scaled", doc: "y = a + s * b, whole-plane: `out = skip + scale * branch` without materialising s*b in another plane. Length is `long`, matching lg_copy rather than lg_add's `int`." },
    Op { name: "lg_upsample2x_nearest", doc: "Nearest-neighbour 2x upsample, NCHW: out[c][oy][ox] = in[c][oy/2][ox/2]. The integer halving is the CONTRACT - it is what PyTorch's F.interpolate(scale_factor=2, mode='nearest') does; mapping through (o+0.5)/2 gives different pixels. grid = (ceil(2w/32), ceil(2h/8)), block = (32,8,1)." },
    Op { name: "lg_pixel_unshuffle2", doc: "Space-to-depth: [C][H][W] -> [4C][H/2][W/2] with output channel c*4 + dy*2 + dx from input channel c at (2y+dy, 2x+dx) - PyTorch's pixel_unshuffle(x, 2). The PERMUTATION is the contract, not just the shape: a following conv's weights are ordered by it. grid = (ceil((w/2)/32), ceil((h/2)/8)). NOT lg_merge_2x2, which merges the same taps into a token-major layout." },
    Op { name: "lg_pixel_shuffle", doc: "Depth-to-space, the INVERSE of lg_pixel_unshuffle2: [r*r*C][H][W] -> [C][r*H][r*W] with output channel c at (r*y+dy, r*x+dx) taken from input channel c*r*r + dy*r + dx at (y, x) - PyTorch's pixel_shuffle(x, r). The PERMUTATION is the contract, not just the shape, exactly as for the unshuffle: a following conv's weights are ordered by it. `r` is a RUNTIME argument because hat-rs launches r = 2 (its x4 octaves) and r = 3 (its x3 head) from one place; r == 2 and r == 3 are written out separately - at the same grid the generic division is 6-8% slower at r == 2, which would be a regression against the fixed-2 copies this replaces - and any other r takes the exact but untuned generic form. grid = (ceil(r*w/32), ceil(r*h/8), c), block = (32, 8, 1)." },
    Op { name: "lg_fft2_r2c", doc: "Batched 2-D real-to-complex FFT. in is [batch][n][n] row-major, out is [batch][n][n/2+1] INTERLEAVED complex - the half spectrum rfftn defines. n <= 64 (the plane lives in shared memory), nb = log2(n) selects the bit-reversal width. UNNORMALISED, like cuFFT: pass scale = 1.0f and apply 1/sqrt(n*n) yourself, or fold the ortho factor in by passing it as scale. grid = (batch, 1, 1), block = (256, 1, 1), no dynamic shared memory." },
    Op { name: "lg_fft2_c2r", doc: "Batched 2-D complex-to-real inverse FFT: in is the [batch][n][n/2+1] interleaved half spectrum lg_fft2_r2c produces, out is [batch][n][n] real. The full spectrum is rebuilt by conjugate symmetry internally, so the caller stores only the half spectrum. UNNORMALISED: pass scale = 1/sqrt(n*n) for the ortho inverse (and undo any scale the forward folded in). grid = (batch, 1, 1), block = (256, 1, 1)." },
    Op { name: "lg_linear_rb", doc: "The SAME op as `lg_linear` (token layout, out[i*C_out + o] = bias[o] + sum_c x[i*C_in + c] * w[o*C_in + c], c ascending, bias added last), with a 4x4 register tile per thread instead of one output element. 2.0x `lg_linear` on the vision shapes that promoted it, and bit-identical to it on the same input. grid = (ceil(c_out/64), ceil(rows/64), 1), block = (16,16,1) = 256 threads, no dynamic shared memory." },
    Op { name: "lg_conv1x1_rb", doc: "The SAME op as `lg_conv1x1` (NCHW 1x1: out[o*plane + p] = bias[o] + sum_c w[o*c_in + c] * in[c*plane + p], plane = h*w, c ascending, bias folded into the accumulator first), register-tiled 4x4. That bias order is what `lg_conv1x1` does, and both are reproduced exactly, so swapping is bit-exact. grid = (ceil(plane/64), ceil(c_out/64), 1), block = (16,16,1)." },
    Op { name: "lg_conv1x1_tile", doc: "The SAME op as `lg_conv1x1`, with both tiles staged in shared memory and 32 accumulators per thread, for a VERY WIDE output over a small plane: at 15232 output channels an 8-channel tile re-reads the input 1904 times against 476 for a 32-channel one, and that input re-read - not the arithmetic - is the whole cost. Measured 5.3x `lg_conv1x1` at 128->128 over 512x512 and 4.1x at 128->15232 over 64x128, but it LOSES 0.7x at 64x64, so a caller with a small plane should use `lg_conv1x1` or `lg_conv1x1_rb`. Order: c ascending, but the BIAS IS APPLIED AFTER THE SUM where both of those fold it in FIRST, so it is NOT bit-compatible with either. Extra args: act (0 none, 1 relu, 2 lrelu with slope act_p). grid = (ceil(wd/128), ceil(h/4), ceil(c_out/32)), block = (32,4,1), static shared memory only." },
    Op { name: "lg_layer_norm_warp", doc: "LayerNorm as `lg_layer_norm`, one WARP per row, for NARROW rows: a row of up to 128 is held in one lane's registers, so x is read once and written once instead of three times. Same reduction tree, same one-pass variance. grid = (ceil(nrows/8), 1, 1), block = (256,1,1). Use `lg_layer_norm` for wide rows." },
    Op { name: "lg_conv2x2s2", doc: "2x2 convolution, stride 2, no padding, nullable bias: out[oc][y][x] = bias[oc] + sum_{ky,kx,ci} w[oc][ci][ky][kx] * in[ci][2y+ky][2x+kx]. Order: ky, kx, ci. Eight output channels per thread, which is where the reuse is - at stride 2 with a 2x2 kernel, an input element feeds exactly one output's tap set. grid = (ceil((h/2)*(w/2)), ceil(c_out/8), 1), block = (256,1,1)." },
    Op { name: "lg_conv_t2x2", doc: "The transposed twin of `lg_conv2x2s2`: out[oc][2y+ky][2x+kx] = bias[oc] + sum_ci w[ci][oc][ky][kx] * in[ci][y][x], NO tap flip, weight layout [c_in][c_out][2][2] (torch's ConvTranspose2d) - not the forward form's [c_out][c_in][2][2]. Order: ci. grid = (ceil(4*h*w), ceil(c_out/8), 1), block = (256,1,1)." },
    Op { name: "lg_window_gather", doc: "Swin window assembly, NCHW plane -> [nw][n][c] tokens with n = win*win. The shift is a CYCLIC offset applied as a modulo wrap on both axes (the reference rolls the plane by -shift before windowing). `w0` is the chunk's first window index, 0 for a whole plane, so a caller that bounds its token count passes the base. grid = (ceil(nw*n*c/256), 1, 1), block = (256,1,1)." },
    Op { name: "lg_window_scatter", doc: "The inverse of `lg_window_gather` at the same shift: `scatter(gather(p)) == p` for every element. Same arguments, same grid." },
];

/// Kernel names, for a completeness check against a loaded module.
pub static NAMES: &[&str] = &[
    "lg_noop",
    "lg_rms_norm",
    "lg_layer_norm",
    "lg_layer_norm_2pass",
    "lg_rope_neox",
    "lg_rope_2d",
    "lg_silu_mul",
    "lg_gelu_tanh",
    "lg_gelu_erf",
    "lg_relu",
    "lg_sigmoid",
    "lg_add",
    "lg_mul",
    "lg_add_inplace",
    "lg_scale",
    "lg_row_affine",
    "lg_channel_layer_norm",
    "lg_channel_affine",
    "lg_channel_scale",
    "lg_copy",
    "lg_channel_mean",
    "lg_argmax",
    "lg_conv1x1",
    "lg_conv3x3s1p1",
    "lg_conv3x3_winograd",
    "lg_conv3x3_tile",
    "lg_conv3x3_q2",
    "lg_conv3x3_q2ng2",
    "lg_conv3x3_catq0",
    "lg_conv3x3_catq0ng2",
    "lg_conv4x4s4",
    "lg_conv_kxk",
    "lg_linear_1x1",
    "lg_extract_rows",
    "lg_merge_2x2",
    "lg_get_row_q8_0_aligned",
    "lg_copy_row",
    "lg_set_i32",
    "lg_attn_gqa",
    "lg_attn_flash",
    "lg_attn_prefill_scores",
    "lg_attn_prefill_softmax",
    "lg_attn_prefill_out",
    "lg_linear",
    "lg_f32_gemm",
    "lg_f32_gemm_tiled",
    "lg_quantize_q8_0",
    "lg_q8_0_gemm_dp4a",
    "lg_q8_0_gemm_aligned",
    "lg_q8_0_gemv",
    "lg_lrelu",
    "lg_add_scaled",
    "lg_upsample2x_nearest",
    "lg_pixel_unshuffle2",
    "lg_pixel_shuffle",
    "lg_fft2_r2c",
    "lg_fft2_c2r",
    "lg_linear_rb",
    "lg_conv1x1_rb",
    "lg_conv1x1_tile",
    "lg_layer_norm_warp",
    "lg_conv2x2s2",
    "lg_conv_t2x2",
    "lg_window_gather",
    "lg_window_scatter",
];

/// Is this name part of the shipped set?
pub fn has(name: &str) -> bool {
    NAMES.contains(&name)
}
